###
POST http://localhost:8080/api/v1/activities/add
Content-Type: application/json

{
  "cycle_id":4500000,
  "activity_reference_id":45,
  "duration_min": 852
}

###
GET http://localhost:8080/api/v1/activities/all_data
Content-Type: application/json


###
PUT http://localhost:8080/api/v1/activities/update/2
Content-Type: application/json

{
  "cycle_id":111,
  "activity_reference_id":222,
  "duration_min": 333
}

###
DELETE http://localhost:8080/api/v1/activities/delete/2
Content-Type: application/json