// ------------------------
//     cycles endpoints
// ------------------------

###
POST http://localhost:8080/api/v1/cycle/add
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2ODU0NDQzODV9.1pT77AYtCmGPXQKCm6ha9gvAppedc-vncNPZ8UVM7sw

{

}

###
GET http://localhost:8080/api/v1/cycle/all_data
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2ODU0NDQzODV9.1pT77AYtCmGPXQKCm6ha9gvAppedc-vncNPZ8UVM7sw


###
PUT http://localhost:8080/api/v1/cycle/update/34
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2ODU0NDQzODV9.1pT77AYtCmGPXQKCm6ha9gvAppedc-vncNPZ8UVM7sw

{
  "new_date":"2023-05-30 09:00:00"
}


###
DELETE http://localhost:8080/api/v1/cycle/delete/30
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2ODU0NDQzODV9.1pT77AYtCmGPXQKCm6ha9gvAppedc-vncNPZ8UVM7sw
