###
POST http://localhost:8080/api/v1/medical_appointments/add
Content-Type: application/json

{
"created_at": "2023-05-30 09:00:00",
"doctor_type": "general doctor", 
"personal_notes": "test put",
"doctor_notes": "test hello"
}

###
GET http://localhost:8080/api/v1/medical_appointments/all_data
Content-Type: application/json


###
PUT http://localhost:8080/api/v1/medical_appointments/update/2
Content-Type: application/json

{
"created_at": "2023-05-30 09:00:00",
"doctor_type": "general doctor", 
"personal_notes": "test put",
"doctor_notes": "test put"
}

###
DELETE http://localhost:8080/api/v1/medical_appointments/delete/2
Content-Type: application/json