// ------------------------
//     User endpoints
// ------------------------

###
POST http://localhost:8080/api/v1/user/register
Content-Type: application/json

{
    "username":"momo2",
    "password":"123",
    "role":"client",
    "email":"momo2@endpoint.com",
    "birth_date":"1990-7-8"
}

###
POST http://localhost:8080/api/v1/user/login
Content-Type: application/json

{
    "username":"momo",
    "password":"123"
}

###
PUT http://localhost:8080/api/v1/user/update
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY5NDg2MjQ5NH0.LfQNtL5U864juuROt9A5YsLT-dKpj3O-ZUVxdOv6dS8

{
    "username":"Marco",
    "email":"marco@endpoint.com",
    "birth_date":"23-12-1990"
}


###
PUT http://localhost:8080/api/v1/user/update_password
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY5NDg2MjQ5NH0.LfQNtL5U864juuROt9A5YsLT-dKpj3O-ZUVxdOv6dS8

{
    "new_password":"new password"

}


###
// you will get all data related to user by id (user_id is in the token after register / login)
GET http://localhost:8080/api/v1/user/data
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY5NDg2MjQ5NH0.LfQNtL5U864juuROt9A5YsLT-dKpj3O-ZUVxdOv6dS8